from __future__ import annotations

from venue_finder.core.models import Venue


def sample_venues() -> list[Venue]:
    return [
        Venue(
            source_name="demo",
            source_url="https://example.com/venue/demo-1",
            name="Forest Lodge Frankfurt",
            website="https://example.com/venue/demo-1",
            venue_type="gruppenhaus",
            city="Wiesbaden",
            country="Germany",
            latitude=50.0833,
            longitude=8.2398,
            maximum_guests=60,
            indoor_sleeping_capacity=40,
            number_of_rooms=12,
            number_of_beds=28,
            camping_allowed=True,
            camper_van_allowed=True,
            parties_allowed=True,
            loud_music_allowed=True,
            dj_allowed=True,
            sound_system_available=True,
            outdoor_party_area=True,
            bbq_available=True,
            fire_place=True,
            private_property=True,
            quiet_hours_start="23:00",
            price_per_night=950.0,
            minimum_nights=2,
            rating=4.7,
            number_of_reviews=41,
            raw_text="Private party house with camping, BBQ, DJ setup and outdoor area. Quiet hours after 23:00.",
        ),
        Venue(
            source_name="demo",
            source_url="https://example.com/venue/demo-2",
            name="Riverside Event Farm",
            website="https://example.com/venue/demo-2",
            venue_type="eventlocation",
            city="Mainz",
            country="Germany",
            latitude=49.9929,
            longitude=8.2473,
            maximum_guests=48,
            indoor_sleeping_capacity=30,
            number_of_rooms=8,
            number_of_beds=20,
            camping_allowed=False,
            camper_van_allowed=False,
            parties_allowed=True,
            loud_music_allowed=False,
            dj_allowed=False,
            sound_system_available=False,
            outdoor_party_area=True,
            bbq_available=True,
            fire_place=False,
            private_property=True,
            quiet_hours_start="22:00",
            price_per_night=780.0,
            minimum_nights=1,
            rating=4.5,
            number_of_reviews=19,
            raw_text="Private event farm with outdoor area and BBQ. No loud music after 22:00.",
        ),
        Venue(
            source_name="demo",
            source_url="https://example.com/venue/demo-3",
            name="Country Group House",
            website="https://example.com/venue/demo-3",
            venue_type="gruppenhaus",
            city="Darmstadt",
            country="Germany",
            latitude=49.8728,
            longitude=8.6512,
            maximum_guests=70,
            indoor_sleeping_capacity=55,
            number_of_rooms=15,
            number_of_beds=44,
            camping_allowed=True,
            camper_van_allowed=False,
            parties_allowed=True,
            loud_music_allowed=True,
            dj_allowed=False,
            sound_system_available=True,
            outdoor_party_area=True,
            bbq_available=True,
            fire_place=False,
            swimming_pool=True,
            private_property=True,
            quiet_hours_start=None,
            price_per_night=1200.0,
            minimum_nights=2,
            rating=4.9,
            number_of_reviews=57,
            raw_text="Large private group house with swimming pool, camping allowed, BBQ and outdoor party area.",
        ),
    ]

